### ISSUE TITLE
Permission Denied When Creating sysinternalsEBPF_offsets.conf

### ISSUE THREAD

**Issue by radams2023** [Sysinternals/SysinternalsEBPF#20]
Hello, 

Any ideas on my I would be getting permission denied when trying to create the sysinternalsEBPF_offsets.conf file. Bellow is the working directory and command I am running. 

/opt/sysinternalsEBPF/getOffsets$ **sudo make conf > /opt/sysinternalsEBPF/sysinternalsEBPF_offsets.conf**

-bash: /opt/sysinternalsEBPF/sysinternalsEBPF_offsets.conf: **Permission denied**

Thanks
RA

**Comment by MarioHewardt** [comment]
Hi - The reason you are getting "Permission denied" is that the redirection is performed by the shell and not sudo and shell (unless ran as root) does not have access to /opt/sysinternalsEBPF. You could pipe it to a location that the shell has access to and then copy the file using sudo to  /opt/sysinternalsEBPF.

**Comment by radams2023** [comment]
Hello Mario, 

When I try that, I get the below error:

make: ./extractOffsets: Command not found
make: *** [Makefile:35: conf] Error 127

The files in my working directory are: extractOffsets.c  getOffsets.c  LICENSE  Makefile  mount.h  README.md

Any ideas? 

Thanks
RA

**Comment by radams2023** [comment]
I su to root and get the same error. 

make: ./extractOffsets: Command not found
make: *** [Makefile:35: conf] Error 127

**Comment by MarioHewardt** [comment]
Did you run (while in /opt/sysinternalsEBPF/getOffsets):

$ sudo make 
$ sudo make conf > ~/sysinternalsEBPF_offsets.conf
$ sudo cp ~/sysinternalsEBPF_offsets.conf /opt/sysinternalsEBPF

What distro/kernel?

**Comment by radams2023** [comment]
After I su to root and ran the make. That did the trick. Running as sudo would not work for some reason. I have sysmon installed and the config file loaded. 

Side note, do you know of any additional config project for Linux. This is what I found so far: https://gist.github.com/Cyb3rWard0g/bcf1514cc340197f0076bf1da8954077

Thanks for all your help!
RA

**Comment by MarioHewardt** [comment]
There are a number of Sysmon config files out there for Windows and Linux. Please note that both Windows and Linux versions share the same config engine so they should be transferable. Of course, Sysmon for Linux doesn't support all the events of the Windows version as of yet (some events do not make sense on Linux and we may add other that do not make sense on Windows) but the general schema itself should be applicable.
