### ISSUE TITLE
Getting a per_buffer setup error when initializing the Sysmon service.

### ISSUE THREAD

**Issue by madsenjack** [Sysinternals/SysinternalsEBPF#21]
Hello, if anyone could shed some light on as to why I am experiencing this error it would be greatly appreciated. I have followed the SysinternalsEBPF installation guide and SysmonForLinux guide to a T, and have preemptively built the getOffsets configuration to prevent previously encountered issues.  

This same configuration and setup has worked previously on separate machines, so I am quite confused on what could be causing this. 

![Screenshot from 2023-02-02 11-17-56](https://user-images.githubusercontent.com/99513198/216380915-ff5915e5-1c73-4fd3-a0b1-ca0db003a336.png)

**Comment by MarioHewardt** [comment]
Hi - thanks for reporting this. I'm closing this issue in favor of the one you opened on the Sysmon For Linux repo.
