### ISSUE TITLE
When compiling the code, getting .>> "Fatal error: linux/openat2.h: No such file..."

### ISSUE THREAD

**Issue by GhostKeep** [Sysinternals/SysinternalsEBPF#23]
Uname -a 
Linux ubuntusrvb-vm-2004 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

  CC       sharedobjs/usdt.o
  CC       libbpf.so.1.1.0
[ 16%] No install step for 'libbpf'
[ 19%] Completed 'libbpf'
[ 19%] Built target libbpf
[ 21%] Extracting unameOffsets.c
[ 23%] Extracting sysinternalsEBPFoffsets.h
[ 26%] Extracting unameOffsets.h
Scanning dependencies of target sysinternalsEBPF
[ 28%] Building C object CMakeFiles/sysinternalsEBPF.dir/telemetryLoader.c.o
In file included from /root/SysinternalsEBPF/telemetryLoader.c:45:
/root/SysinternalsEBPF/build/libbpf/src/libbpf/include/uapi/linux/fcntl.h:6:10: fatal error: linux/openat2.h: No such file or directory
    6 | #include <linux/openat2.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sysinternalsEBPF.dir/build.make:78: CMakeFiles/sysinternalsEBPF.dir/telemetryLoader.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/sysinternalsEBPF.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@ubuntusrvb-vm-2004:~/SysinternalsEBPF/build#

**Comment by MarioHewardt** [comment]
I opened an issue on libbpf for this (https://github.com/libbpf/libbpf/issues/649). For now, you should be able to copy that file from the linux sources as a workaround.
