### ISSUE TITLE
Is openeuler supported?

### ISSUE THREAD

**Issue by SuperWhite18** [Sysinternals/SysinternalsEBPF#40]
I want to install it on Openeuler，if supported, please update build.md.  So Thanks!!!

**Comment by MarioHewardt** [comment]
Hi - while we strive to test on as many distros as possible, the ones we currently support and have tested on are the ones in the install and build documents. Generally speaking, if the distro is relatively new and supports eBPF you could always try building/testing it and see how it goes.
